version: '3'

services:
  postgres:
    image: postgres
    container_name: db_foods
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_foods